name: halopaket
description: sample membuat package.
version: 0.0.1
author: triyono <yono.tri@gmail.com>
homepage: https://github.com/triyono777/praxis-academy/tree/master/novice/04-02/halopaket

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.halopaket
    pluginClass: HalopaketPlugin
